

import Head from 'next/head'
//import Image from 'next/image'
import Link from 'next/link';
import { Box, Button, Stack, Typography } from '@mui/material';

// Components


export default function Dashboard() {
  return (
    <>
      <Head>
        {/* TODO */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Stack gap={1}>
          <Box>
            <Typography>
              Welcome On Dashboard
            </Typography>
          </Box>
        </Stack>
      </main>
    </>
  )
}
