

import React from "react";
import Head from 'next/head';
import Link from 'next/link';
import { Box, Button, Stack, Typography } from '@mui/material';
import { selectUser } from '@/redux/slices/userSlice';
import { useSelector } from 'react-redux';
import useHomeRedirect from '@/hooks/redirects/useHomeRedirect';
import { PAGE_PADDING_X, PAGE_PADDING_TOP } from "@/constants/globalConstants";

export default function Dashboard() {

  // States
  const user  = useSelector(selectUser);
  
  // Redirect when logout
  useHomeRedirect()

  return (
    <>
      <Head>
        {/* TODO */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Stack gap={1} px={PAGE_PADDING_X} py={PAGE_PADDING_TOP}>
          <Box>
            <Typography>
              Welcome On Dashboard {user?.displayName}
            </Typography>
          </Box>

          <Stack flexDirection="row" gap={2}>
            <Box>
              <Link href="/createproject">
                <Button 
                  variant="contained"
                >
                  Create Collab Project
                </Button>
              </Link>
            </Box>

            <Box>
              <Link href="/findproject">
                <Button 
                  variant="contained"
                >
                  Find Collab Project
                </Button>
              </Link>
            </Box>
          </Stack>

        </Stack>
      </main>
    </>
  )
}
