import React from "react";
import Head from 'next/head';
import Link from 'next/link';
import { Box, Button, Stack } from '@mui/material';
import useHomeRedirect from '@/hooks/redirects/useHomeRedirect';
import { PAGE_PADDING_X, PAGE_PADDING_TOP, MAX_WIDTH } from "@/constants/globalConstants";

// Components
import Timeline from "@/components/content/Timeline";

export default function Dashboard() {
  
  // Redirect when logout
  useHomeRedirect()

  return (
    <>
      <Head>
        {/* TODO */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Stack 
          alignItems="center" 
          px={PAGE_PADDING_X} 
          py={PAGE_PADDING_TOP}
        >
          <Stack maxWidth={MAX_WIDTH} width="100%">
            <Stack 
              gap={2} 
              flexDirection="row" 
              justifyContent="center"
            >
              <Box pt={2}>
                <Link href="/createproject" passHref legacyBehavior>
                  <Button 
                    variant="contained"
                    color="error"
                  >
                    Create Collab
                  </Button>
                </Link>
              </Box>
            </Stack>

            <Timeline />
          </Stack>
        </Stack>
      </main>
    </>
  )
}
