import Head from 'next/head'
//import Image from 'next/image'
import Link from 'next/link';
import { Button, Stack } from '@mui/material';

// Components


export default function Home() {
  return (
    <>
      <Head>
        {/* TODO */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Stack gap={1}>
          <Link href="/signin">
          <Button variant="contained">
              sign in
            </Button>
          </Link>

          <Link href="/signup">
            <Button variant="contained">
              sign up
            </Button>
          </Link>
        </Stack>
      </main>
    </>
  )
}
