import React, { useState } from 'react';
import Head from 'next/head'
//import Image from 'next/image'
import { Box, Stack, Typography } from '@mui/material';
import { signInWithEmailAndPassword } from 'firebase/auth';
import { auth } from '@/config/firebase';
import useDashboardRedirect from '@/hooks/useDashboardRedirect';

// Components
import SignInUp from '@/components/auth/SignInUp';
import GoogleSignUp from '@/components/auth/GoogleSingnUp';

export default function Signin() {
  
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  // TODO type
  const handleSignIn = async () => {
    setError('');

    try {
      await signInWithEmailAndPassword(auth, email, password);
      setSuccess('Successfully signed in!')
    } catch (err) { 
      if (err instanceof Error) {
        setError(err.message);
        //alert('Error signing in. Please try again.');
      } else {
        console.error('Unexpected error', err);
      }
    }
  };

  useDashboardRedirect();

  return (
    <>
      <Head>
        {/* TODO */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Stack gap={1}>
          <Box>
            <Typography>
              LETS SIGN IN
            </Typography>
          </Box>

          <SignInUp 
            setEmail={setEmail}
            setPassword={setPassword}
            handler={handleSignIn}
            success={success}
            error={error}
            text="Sign In"
          />

          <GoogleSignUp />
          
        </Stack>
      </main>
    </>
  )
}
