import Head from 'next/head'
import { createUserWithEmailAndPassword } from 'firebase/auth';
import { auth } from '@/config/firebase';
import { useState } from 'react';

// Components
import SignInUp from '@/components/auth/SignInUp';
import GoogleSignUp from '@/components/auth/GoogleSingnUp';


export default function Signup() {
  
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  // TODO type
  const handleSignUp = async () => {
    setError('');
    setSuccess('');

    try {
      // Firebase sign-up method
      await createUserWithEmailAndPassword(auth, email, password);
      setSuccess('Account created successfully!');
    } catch (err: any) {
      setError(err.message); // Display error message
    }
  };

  return (
    <>
      <Head>
        {/* TODO */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SignInUp 
          setEmail={setEmail}
          setPassword={setPassword}
          handler={handleSignUp}
          success={success}
          error={error}
        />

        <GoogleSignUp />

      </main>
    </>
  )
}
